### PR TITLE
Latest master from upstream

### PR DESCRIPTION
**Pull request by pombredanne**

### CODE REVIEW

**Comment by pombredanne** [comment]
@Quentin-M and team: thanks!

**Comment by Quentin-M** [comment]
@pombredanne Big changes coming soon too :) See https://github.com/Quentin-M/clair/tree/sql

**Comment by pombredanne** [comment]
@Quentin-M I saw that ... Just curious about the why? cayley choked? bugged? or is not mainline enough? any other reason?

**Comment by Quentin-M** [comment]
@pombredanne Too slow for Clair's usage (especially at scale) and some important features are missing (ie. pagination, which is really important for notifications).

**Pull request merged**
